Data was downloaded from https://www.fec.gov/data/browse-data/?tab=bulk-data

There are 21 different txt files that we want to join together into one dataframe to join with election data.  This data contains campaign finance infomation from 1979 - 2020.

In [1]:
import pandas as pd

In [10]:
# import txt file from FEC
data00 = pd.read_csv("txt/weball00.txt", sep="|", header=None)
# file doesn't contain headers, but they were available from the file description 
# https://www.fec.gov/campaign-finance-data/all-candidates-file-description/
columnNames = ["cand_id", "cand_name", "cand_ici", "pty_cd", "cand_pty_affiliation", "ttl_receipts", "trans_form_auth", "ttl_disb", "trans_to_auth", "coh_bop", "coh_cop", "cand_contrib", "cand_loans", "other_loans", "cand_loan_repay", "other_loan_repay", "debts_owed_by", "ttl_indiv_contrib", "cand_office_st", "cand_office_district", "spec_election", "prim_election", "run_election", "gen_election", "gen_election_precent", "other_pol_cmte_contrib", "pol_pty_contrib", "cvg_end_dt", "indiv_refunds", "cmte_refunds"]
data00.columns = columnNames
data00.head()

,cand_id,cand_name,cand_ici,pty_cd,cand_pty_affiliation,ttl_receipts,trans_form_auth,ttl_disb,trans_to_auth,coh_bop,...,spec_election,prim_election,run_election,gen_election,gen_election_precent,other_pol_cmte_contrib,pol_pty_contrib,cvg_end_dt,indiv_refunds,cmte_refunds
0,H0AK00055,"GREENE, CLIFFORD MARK",C,1,DEM,464.0,0.0,462.0,0,0.0,...,NaN,W,NaN,L,16.0,0.0,0.0,12/31/2000,0.0,0
1,H4AK00057,"VONDERSAAR, FRANK J",C,1,DEM,885.0,0.0,884.0,0,0.0,...,NaN,L,NaN,NaN,0.0,0.0,0.0,09/15/2000,0.0,0
2,H6AK01019,"LINCOLN, GEORGIANNA",C,1,DEM,0.0,0.0,1753.0,0,2391.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12/31/2000,0.0,0
3,H8AK00074,"DUNCAN, JIM (JAMES W DUNCAN)",C,1,DEM,37591.0,0.0,38808.0,0,1216.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,01/31/2000,1000.0,0
4,H8AK00082,"PECHEK, STU",C,1,DEM,12274.0,0.0,232.0,0,232.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,01/25/1999,0.0,0

In [32]:
data00.shape

(2604, 30)

In [21]:
#import all files in a folder, instead of just one at a time
import glob

#import all files
path = r'/Users/lrsterngmail.com/desktop/Flatiron/Mod_3_Project/txt' 
all_files = glob.glob(path + "/*.txt")

li = []

#turn files into dataframes
for filename in all_files:
    df = pd.read_csv(filename, sep="|", index_col=None, header=None, error_bad_lines=False)
    li.append(df)

#join all dataframes together
frame = pd.concat(li, axis=0, ignore_index=True)

In [25]:
frame.head()

,cand_id,cand_name,cand_ici,pty_cd,cand_pty_affiliation,ttl_receipts,trans_form_auth,ttl_disb,trans_to_auth,coh_bop,...,spec_election,prim_election,run_election,gen_election,gen_election_precent,other_pol_cmte_contrib,pol_pty_contrib,cvg_end_dt,indiv_refunds,cmte_refunds
0,H0AK00014,"WHITTAKER, RICHARD",NaN,1,DEM,1116.0,0.0,764.0,0.0,0.0,...,NaN,L,NaN,L,0.0,0.0,0.0,10/15/1980,0.0,0.0
1,H0AK01012,"PARNELL, KEVIN ""PAT""",NaN,1,DEM,51643.0,0.0,51607.0,0.0,0.0,...,NaN,W,NaN,L,26.0,0.0,0.0,12/31/1980,0.0,0.0
2,H6AK00029,"HENSLEY, WILLIAM L.",NaN,1,DEM,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12/31/1980,0.0,0.0
3,H6AK00102,"HOPSON, EBEN",NaN,1,DEM,0.0,0.0,390.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12/31/1980,0.0,0.0
4,H8AK00025,"RODEY, PATRICK",NaN,1,DEM,6057.0,0.0,2919.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12/31/1980,0.0,0.0

In [23]:
#change column names
frame.columns = columnNames

In [26]:
frame.head()

,cand_id,cand_name,cand_ici,pty_cd,cand_pty_affiliation,ttl_receipts,trans_form_auth,ttl_disb,trans_to_auth,coh_bop,...,spec_election,prim_election,run_election,gen_election,gen_election_precent,other_pol_cmte_contrib,pol_pty_contrib,cvg_end_dt,indiv_refunds,cmte_refunds
0,H0AK00014,"WHITTAKER, RICHARD",NaN,1,DEM,1116.0,0.0,764.0,0.0,0.0,...,NaN,L,NaN,L,0.0,0.0,0.0,10/15/1980,0.0,0.0
1,H0AK01012,"PARNELL, KEVIN ""PAT""",NaN,1,DEM,51643.0,0.0,51607.0,0.0,0.0,...,NaN,W,NaN,L,26.0,0.0,0.0,12/31/1980,0.0,0.0
2,H6AK00029,"HENSLEY, WILLIAM L.",NaN,1,DEM,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12/31/1980,0.0,0.0
3,H6AK00102,"HOPSON, EBEN",NaN,1,DEM,0.0,0.0,390.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12/31/1980,0.0,0.0
4,H8AK00025,"RODEY, PATRICK",NaN,1,DEM,6057.0,0.0,2919.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12/31/1980,0.0,0.0

In [28]:
frame.shape

(54164, 30)

In [33]:
#import information on the file
data = pd.read_csv("All candidates file format - Sheet1.csv", header=0)

In [34]:
#information about the dataset
data

,Column name,Field name,Position,Null,Data type,Description,Example data
0,CAND_ID,Candidate identification,1,N,VARCHAR2 (9),NaN,H8VA01233
1,CAND_NAME,Candidate name,2,Y,VARCHAR2(200),NaN,Martha Washington
2,CAND_ICI,Incumbent challenger status,3,Y,VARCHAR2(1),NaN,I
3,PTY_CD,Party code,4,Y,VARCHAR2(1),NaN,NON
4,CAND_PTY_AFFILIATION,Party affiliation,5,Y,VARCHAR2(3),NaN,NON
5,TTL_RECEIPTS,Total receipts,6,Y,"Number(14,2)",NaN,"345,456.34"
6,TRANS_FROM_AUTH,Transfers from authorized committees,7,Y,"Number(14,2)",NaN,4000
7,TTL_DISB,Total disbursements,8,Y,"Number(14,2)",NaN,175645.21
8,TRANS_TO_AUTH,Transfers to authorized committees,9,Y,"Number(14,2)",NaN,0
9,COH_BOP,Beginning cash,10,Y,"Number(14,2)",NaN,845901.23
10,COH_COP,Ending cash,11,Y,"Number(14,2)",NaN,915671.43
11,CAND_CONTRIB,Contributions from candidate,12,Y,"Number(14,2)",NaN,500
12,CAND_LOANS,Loans from candidate,13,Y,"Number(14,2)",NaN,250000
13,OTHER_LOANS,Other loans,14,Y,"Number(14,2)",NaN,0
14,CAND_LOAN_REPAY,Candidate loan repayments,15,Y,"Number(14,2)",NaN,100000
15,OTHER_LOAN_REPAY,Other loan repayments,16,Y,"Number(14,2)",NaN,0
16,DEBTS_OWED_BY,Debts owed by,17,Y,"Number(14,2)",NaN,250
17,TTL_INDIV_CONTRIB,Total individual contributions,18,Y,"Number(14,2)",NaN,450000
18,CAND_OFFICE_ST,Candidate state,19,Y,VARCHAR2(2,NaN,VA
19,CAND_OFFICE_DISTRICT,Candidate district,20,Y,VARCHAR2(2),NaN,1
20,SPEC_ELECTION,Special election status,21,Y,VARCHAR2(1),Election result data included in 1996-2006 fil...,W
21,PRIM_ELECTION,Primary election status,22,Y,VARCHAR2(1),Election result data included in 1996-2006 fil...,L
22,RUN_ELECTION,Runoff election status,23,Y,VARCHAR2(1),Election result data included in 1996-2006 fil...,L
23,GEN_ELECTION,General election status,24,Y,VARCHAR2(1),Election result data included in 1996-2006 fil...,W
24,GEN_ELECTION_PRECENT,General election percentage,25,Y,"Number(7,4)",Election result data included in 1996-2006 fil...,63.2
25,OTHER_POL_CMTE_CONTRIB,Contributions from other political committees,26,Y,"Number(14,2)",NaN,200000
26,POL_PTY_CONTRIB,Contributions from party committees,27,Y,"Number(14,2)",NaN,200000
27,CVG_END_DT,Coverage end date,28,Y,DATE(MM/DD/YYYY),Through date,10/19/2018
28,INDIV_REFUNDS,Refunds to individuals,29,Y,"Number(14,2)",NaN,4000
29,CMTE_REFUNDS,Refunds to committees,30,Y,"Number(14,2)",NaN,100

>The all candidates file contains summary financial information for each candidate who raised or spent money during the period, regardless of when they are up for election.


>The file has one record per candidate and shows information about the candidate, total receipts, transfers received from authorized committees, total disbursements, transfers given to authorized committees, cash-on-hand totals, loans and debts, and other financial summary information. The end-of-line (EOL) marker is line feed '\n' (LF, 0x0A, 10 in decimal).

>**Data timing**
This file is completely dependent on summary information reported by the campaign. The time period covered by this file may be more recent than other data files (like the post-cycle candidate summary file). During the primary election season, the period covered may be different for candidates in different states, depending on their primary dates. Since the data is timelier, some of the information in this file is less precise than information in the post-cycle candidate summary file. For example, breakouts by special interest group code are not possible.

>**Double-counted financial activity**
A candidate’s financial summary may have double-counted financial activity. If a candidate has more than one committee authorized to raise and spend funds on their behalf, the activity in this file combines these committees. If the committees transfer funds back and forth to each other, this activity would be counted twice. Information about “transfers to authorized committees” and “transfers from authorized committees” is included in the file. If there are values in both of these fields, subtract these from the total receipts and total disbursements for a more accurate value of the candidate’s total activity.

In [ ]:
frame['finacial_activity'] = df.apply (lambda row: frame.trans_from_auth - frame.trans_to_auth, axis=1)